### ISSUE TITLE
Create "How It Works" Page

### ISSUE THREAD

**Issue by jessbeutler** [publicdomainmap/publicdomainmap.org#3]
in progress text:

## Licensing
OpenStreetMap data is licensed under [OdBL data license](https://opendatacommons.org/licenses/odbl/). When signing up for an OSM account there is an option to allow data contributions to be used in the public domain, but no mechanism exists to differentiate these data from OdBL data in OpenStreetMap. US government data is required to be licensed as public domain, which has historically limited government contributions and use of OpenStreetMap data. Public Domain Map honors both the OdBL and public domain data licenses and bridges this gap through a creative workflow that allows users to simultaneously contribute to OpenStreetMap and to the federal government as public domain data.

[licensing diagram tbd]

## Tools & Documentation

[tool diagram tbd]

## Road Map & Sustainability

**Comment by jessbeutler** [comment]
Rework this video for general context & update branding: https://www.youtube.com/watch?v=tBDc4i34cj8

**Comment by quincylvania** [comment]
Closing as stale
