### ISSUE TITLE
License page

### ISSUE THREAD

**Issue by quincylvania** [publicdomainmap/publicdomainmap.org#8]
I assume we need a page like https://www.openstreetmap.org/copyright that explicitly states the legal status of the data in the database. Wasn't there something like this before? @jessbeutler

**Comment by jessbeutler** [comment]
Yes, great catch. I am not sure that we have this documented like this yet, but I can set up a page on the pd website.

**Comment by quincylvania** [comment]
This is more important now that people are adding data. All we really need is to assign a [public-domain-equivalent license](https://en.wikipedia.org/wiki/Public-domain-equivalent_license), probably [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/).

**Comment by quincylvania** [comment]
@jessbeutler I'm happy to take this on if you prefer.

**Comment by jessbeutler** [comment]
Feel free to jump ahead on this!
